# Project names should contain only lowercase characters and underscores. 
name: 'dfds_dbt_practice'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"] # This is the model folder for the dbt to understand
analysis-paths: ["analyses"]  # This is the analyses folder for the dbt to understand
test-paths: ["tests"] # This is the tests folder for the dbt to understand
seed-paths: ["seeds"] # This is the seeds folder for the dbt to understand
macro-paths: ["macros"] # This is the macros folder for the dbt to understand
snapshot-paths: ["snapshots"] # This is the snapshots folder for the dbt to understand

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `-- {{config(materialized='view')}} or -- {{config(materialized='table')}}` macro.
models:
  dfds_dbt_practice:
    stage_layer:
      +materialized: view

    mart_layer:
      +materialized: table
